
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 119
#define YY_END_OF_BUFFER 120
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[450] =
    {   0,
        0,    0,  120,  118,    1,    2,  103,  103,  111,  106,
      104,  107,  110,  110,   19,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  118,    1,  113,    0,  112,
      111,    0,  108,  105,  109,  110,  110,  110,   14,  110,
      110,  110,  110,   18,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,   50,   56,  110,  110,  110,  110,  110,
      110,  110,  110,  110,   65,  110,   68,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,

       88,  110,  110,  110,  110,  110,  110,  110,  110,    0,
        0,  116,  112,    0,    0,  114,    5,    6,   13,   15,
      110,    7,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,   43,  110,  110,  110,  110,
      110,  110,  110,    4,   57,  110,  110,   10,    9,  110,
       61,  110,  110,   64,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,   81,  110,  110,
      110,  110,   11,  110,  110,  110,  101,  110,  110,  110,
      110,  110,  110,    0,    0,  115,  110,  110,    8,  110,

       21,  110,  110,  110,  110,  110,  110,  110,  110,  110,
        3,  110,  110,  110,  110,   34,  110,  110,   38,  110,
      110,  102,  110,  110,  110,  110,   46,  110,  110,  110,
      110,  110,  110,  110,   55,  110,   59,  110,   62,  110,
       66,  110,  110,  110,  110,  110,  110,  110,  110,   76,
      110,  110,  110,  110,   82,  110,   84,  110,  110,  110,
      110,  110,   92,  110,  110,   95,  110,  110,   98,   99,
        0,  110,  110,   20,  110,   22,   23,  110,  110,   12,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,   41,   42,  110,   45,   47,   48,  110,

       51,  110,  110,  110,  110,  110,  110,  110,   69,  110,
      110,  110,  110,  110,   75,  110,  110,  110,  110,  110,
      110,   86,   89,  110,  110,  110,  110,  110,   97,    0,
      110,  110,  110,   24,  110,   26,  110,   28,  110,  110,
      110,  110,   33,  110,  110,   37,   39,   40,  110,   49,
      110,   53,  110,  110,   60,  110,   67,  110,  110,  110,
      110,   74,  110,  110,   79,   80,  110,  110,   87,   90,
       91,   93,  110,  110,    0,  110,   17,  110,  110,   27,
      110,   30,   31,   32,  110,  110,   44,  110,   54,  110,
       63,  110,   71,  110,  110,  110,  110,  110,   85,   94,

      110,    0,  110,  110,   25,   29,   35,   36,  110,   58,
      110,  110,  110,  110,   78,   83,   96,    0,  110,   21,
      100,   52,   70,  110,   73,  110,    0,  110,   72,   77,
        0,  110,    0,  110,    0,   16,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  117,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    1,    1,    1,    1,    1,    1,    1,    7,
        7,    8,    9,    7,   10,   11,    1,   12,   13,   13,
       13,   13,   13,   13,   13,   13,   14,    1,    7,   15,
       16,   17,    1,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,    1,   46,    1,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   28,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,   67,   68,   69,   70,
       71,   72,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[73] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    3,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3
    } ;

static yyconst flex_int16_t yy_base[452] =
    {   0,
        0,    0,  271,  949,   71,  949,  949,   66,   70,   58,
      949,  241,   65,   63,  116,  117,   61,  118,   49,   68,
      124,    0,   65,   72,  139,  124,  162,  154,   62,   86,
      206,  169,  171,  187,  220,   73,  105,  197,  250,  265,
      271,  277,  949,  949,  949,    0,  109,  197,   87,  159,
       89,  178,  190,    0,  154,  247,  219,  261,  176,  238,
      258,  277,  260,  264,  271,  192,  278,  270,  276,  274,
      278,  296,  272,  311,    0,  275,  287,  293,  284,  311,
      294,  313,  322,  331,    0,  335,  334,  336,  340,  338,
      346,  337,  338,  344,  335,  356,  341,  348,  352,  366,

        0,  364,  376,  380,  377,  382,  385,  374,  378,  245,
      404,  409,  416,  434,  412,  437,    0,    0,    0,    0,
      383,    0,  390,  403,  410,  409,  431,  417,  424,  418,
      425,  439,  426,  441,  439,  448,  447,  450,  436,  452,
      441,  457,  441,  459,  467,  465,  460,  463,  466,  465,
      481,  487,  488,  490,    0,  487,  493,    0,    0,  479,
        0,  489,  498,    0,  492,  498,  504,  507,  504,  508,
      501,  497,  504,  513,  508,  525,  526,    0,  512,  525,
      537,  543,    0,  537,  535,  552,  533,  534,  553,  535,
      548,  556,  550,  541,  574,  578,  561,  576,    0,  579,

      586,  580,  583,  583,  587,  578,  579,  595,  587,  601,
        0,  592,  605,  587,  589,  593,  603,  602,    0,  599,
      598,    0,  612,  602,  614,  620,    0,  608,  615,  620,
      614,  637,  626,  638,    0,  626,    0,  636,    0,  633,
        0,  639,  637,  648,  657,  651,  656,  654,  640,    0,
      649,  666,  657,  668,    0,  661,    0,  662,  673,  666,
      660,  664,    0,  680,  680,    0,  686,  689,    0,    0,
      695,  681,  697,    0,  700,    0,    0,  686,  696,    0,
      699,  697,  695,  714,  715,  700,  707,  716,  713,  710,
      721,  723,  711,    0,    0,  728,    0,    0,    0,  729,

        0,  736,  720,  737,  742,  743,  740,  739,    0,  735,
      738,  747,  756,  758,    0,  757,  762,  766,  749,  761,
      769,  756,    0,  771,  774,  764,  779,  763,    0,  244,
      777,  774,  773,    0,  773,    0,  775,    0,  779,  788,
      796,  784,    0,  804,  804,    0,    0,    0,  796,    0,
      792,    0,  796,  810,    0,  815,    0,  810,  799,  815,
      804,    0,  813,  826,    0,    0,  817,  828,    0,    0,
        0,    0,  819,  829,  813,  815,    0,  838,  839,    0,
      840,    0,    0,    0,  845,  834,    0,  841,    0,  846,
        0,  842,    0,  853,  846,  858,  855,  848,    0,    0,

      852,  238,  870,  857,    0,  857,    0,    0,  859,    0,
      864,  876,  878,  881,    0,    0,    0,  228,  868,    0,
        0,    0,    0,  872,    0,  874,  220,  886,    0,    0,
      165,  882,    0,  885,  189,    0,  191,  146,  160,  117,
      154,  157,  142,  122,  108,   54,   86,  949,  949,   87,
      945
    } ;

static yyconst flex_int16_t yy_def[452] =
    {   0,
      449,    1,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,

      450,  450,  450,  450,  450,  450,  450,  450,  450,  449,
      449,  449,  449,  449,  449,  449,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  449,  449,  449,  450,  450,  450,  450,

      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      449,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,

      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  449,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  449,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,

      450,  449,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  449,  450,  450,
      450,  450,  450,  450,  450,  450,  449,  450,  450,  450,
      449,  450,  451,  450,  449,  450,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,    0,  449,
      449
    } ;

static yyconst flex_int16_t yy_nxt[1022] =
    {   0,
        4,    5,    6,    4,    5,    5,    7,    7,    4,    4,
        8,    9,    9,    9,   10,   11,   12,    4,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   22,   22,   22,   36,    4,    4,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   22,
       22,   22,   37,   43,   44,   37,   37,   38,   38,   38,
       40,   41,   41,   41,   72,   52,   73,   76,   39,   46,
       77,  110,   42,  448,   47,   53,   48,   66,   78,  447,

       90,   49,   67,   50,   51,   54,   37,  120,   91,   37,
       37,  446,   72,  122,   52,   73,   76,   39,   92,   77,
      110,   42,   47,   53,   48,   66,  445,   78,   90,   49,
       67,   50,   51,   54,   55,   61,  120,   91,  117,   62,
       68,   56,  122,   63,  444,   57,   92,   69,   58,   64,
       70,   59,   65,   71,   60,   74,   82,   79,  443,  442,
       75,  441,   83,   55,   61,   80,  117,  440,   62,   68,
       56,   81,   63,   57,  125,   69,   58,   64,   70,   59,
       65,   71,   60,   74,   82,   84,   79,  100,   75,   88,
       83,  439,   89,   85,   80,   86,  121,   87,  132,   81,

      438,  101,  102,  125,  103,  105,  437,  104,   38,   38,
       38,  433,  142,  106,   84,  123,  100,   88,  118,   39,
       89,   85,  124,   86,  121,   87,   93,  132,   94,  101,
      102,   95,  103,  431,  105,  104,   96,  427,   97,  119,
       98,  142,  106,  123,   99,  107,  108,  118,   39,  418,
      124,  128,  109,  375,  194,   93,   45,   94,  111,  111,
       95,  112,  112,  112,   96,  126,   97,  119,   98,  127,
      449,  449,   99,  133,  107,  108,  113,  113,  113,  128,
      109,   40,   41,   41,   41,  115,  115,  114,  116,  116,
      116,  129,  130,   42,  126,  134,  139,  135,  127,  131,

      136,  133,  140,  141,  143,  449,  137,  144,  145,  146,
      148,  151,  147,  138,  149,  160,  114,  155,  156,  129,
      130,  157,   42,  134,  139,  158,  135,  131,  150,  136,
      140,  141,  152,  143,  137,  144,  145,  146,  148,  151,
      147,  138,  159,  149,  160,  155,  156,  153,  154,  157,
      161,  162,  163,  158,  164,  167,  150,  165,  168,  171,
      172,  152,  169,  176,  173,  449,  175,  179,  170,  174,
      159,  181,  166,  177,  180,  153,  154,  182,  161,  162,
      163,  178,  183,  164,  167,  184,  165,  168,  171,  172,
      185,  169,  176,  173,  175,  179,  170,  186,  174,  181,

      166,  177,  187,  180,  190,  182,  188,  191,  197,  178,
      183,  192,  189,  193,  184,  112,  112,  112,  449,  185,
      112,  112,  112,  116,  116,  116,  186,  113,  113,  113,
      198,  187,  199,  190,  188,  200,  191,  197,  114,  192,
      189,  193,  195,  195,  201,  196,  196,  196,  116,  116,
      116,  202,  449,  203,  204,  205,  206,  207,  198,  210,
      199,  208,  209,  211,  200,  212,  214,  114,  213,  215,
      216,  218,  201,  217,  219,  220,  449,  221,  222,  223,
      202,  203,  204,  205,  206,  224,  207,  225,  210,  208,
      209,  226,  211,  227,  212,  214,  213,  228,  215,  216,

      218,  217,  219,  229,  220,  221,  222,  230,  223,  231,
      233,  236,  234,  232,  224,  237,  225,  238,  239,  226,
      240,  227,  235,  241,  242,  228,  243,  244,  247,  449,
      248,  229,  249,  250,  245,  251,  230,  252,  231,  233,
      236,  234,  232,  246,  237,  238,  239,  253,  254,  240,
      235,  241,  255,  242,  256,  243,  244,  247,  248,  257,
      249,  250,  245,  258,  251,  252,  259,  260,  263,  261,
      262,  246,  264,  265,  449,  266,  253,  254,  270,  267,
      255,  269,  256,  268,  271,  196,  196,  196,  257,  196,
      196,  196,  258,  272,  259,  260,  263,  261,  273,  262,

      264,  274,  265,  266,  275,  277,  270,  267,  276,  278,
      269,  268,  271,  279,  449,  280,  281,  282,  449,  283,
      284,  272,  285,  286,  449,  287,  288,  273,  289,  290,
      274,  291,  292,  275,  277,  293,  276,  294,  278,  295,
      296,  297,  279,  280,  281,  298,  282,  283,  299,  284,
      285,  300,  286,  287,  288,  301,  289,  302,  290,  291,
      292,  303,  304,  293,  305,  306,  294,  295,  307,  296,
      297,  308,  309,  298,  310,  311,  299,  312,  313,  300,
      314,  449,  315,  301,  316,  317,  302,  318,  319,  303,
      320,  304,  305,  306,  321,  322,  307,  323,  324,  308,

      309,  325,  326,  310,  311,  327,  312,  313,  328,  314,
      315,  329,  316,  330,  317,  318,  331,  319,  320,  332,
      333,  336,  321,  334,  322,  323,  324,  335,  337,  325,
      338,  326,  339,  340,  327,  341,  342,  328,  343,  344,
      329,  345,  330,  346,  331,  347,  449,  348,  332,  333,
      336,  334,  349,  350,  351,  335,  337,  352,  338,  353,
      354,  339,  340,  341,  342,  355,  356,  343,  344,  345,
      357,  358,  346,  359,  347,  348,  360,  361,  362,  363,
      364,  349,  350,  351,  365,  352,  366,  367,  353,  354,
      368,  449,  369,  370,  355,  356,  371,  373,  357,  358,

      372,  359,  374,  376,  360,  377,  361,  362,  363,  364,
      378,  379,  380,  365,  366,  381,  367,  382,  383,  368,
      369,  384,  370,  385,  386,  371,  373,  387,  372,  388,
      374,  389,  376,  377,  390,  391,  392,  394,  378,  379,
      380,  393,  395,  381,  396,  382,  397,  383,  398,  384,
      399,  401,  385,  386,  400,  387,  402,  388,  403,  389,
      404,  405,  406,  390,  391,  392,  394,  407,  410,  393,
      395,  408,  396,  409,  411,  397,  398,  412,  414,  399,
      401,  413,  400,  415,  402,  416,  403,  417,  419,  404,
      405,  406,  420,  421,  422,  423,  407,  410,  424,  408,

      425,  409,  411,  426,  449,  428,  412,  414,  429,  413,
      430,  415,  432,  416,  434,  417,  436,  419,  449,  449,
      420,  421,  422,  423,  449,  449,  449,  424,  449,  425,
      449,  449,  426,  428,  449,  449,  429,  449,  430,  449,
      449,  432,  434,  449,  436,  435,  449,  435,    3,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,

      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449
    } ;

static yyconst flex_int16_t yy_chk[1022] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,   10,   10,    5,    5,    8,    8,    8,
        9,    9,    9,    9,   19,   14,   20,   23,    8,  450,
       24,   36,    9,  447,   13,   14,   13,   17,   24,  446,

       29,   13,   17,   13,   13,   14,   37,   49,   30,   37,
       37,  445,   19,   51,   14,   20,   23,    8,   30,   24,
       36,    9,   13,   14,   13,   17,  444,   24,   29,   13,
       17,   13,   13,   14,   15,   16,   49,   30,   47,   16,
       18,   15,   51,   16,  443,   15,   30,   18,   15,   16,
       18,   15,   16,   18,   15,   21,   26,   25,  442,  441,
       21,  440,   26,   15,   16,   25,   47,  439,   16,   18,
       15,   25,   16,   15,   55,   18,   15,   16,   18,   15,
       16,   18,   15,   21,   26,   27,   25,   32,   21,   28,
       26,  438,   28,   27,   25,   27,   50,   27,   59,   25,

      437,   32,   33,   55,   33,   34,  435,   33,   38,   38,
       38,  431,   66,   34,   27,   52,   32,   28,   48,   38,
       28,   27,   53,   27,   50,   27,   31,   59,   31,   32,
       33,   31,   33,  427,   34,   33,   31,  418,   31,   48,
       31,   66,   34,   52,   31,   35,   35,   48,   38,  402,
       53,   57,   35,  330,  110,   31,   12,   31,   39,   39,
       31,   39,   39,   39,   31,   56,   31,   48,   31,   56,
        3,    0,   31,   60,   35,   35,   40,   40,   40,   57,
       35,   41,   41,   41,   41,   42,   42,   40,   42,   42,
       42,   58,   58,   41,   56,   61,   63,   62,   56,   58,

       62,   60,   64,   65,   67,    0,   62,   68,   69,   70,
       71,   73,   70,   62,   72,   81,   40,   76,   77,   58,
       58,   78,   41,   61,   63,   79,   62,   58,   72,   62,
       64,   65,   74,   67,   62,   68,   69,   70,   71,   73,
       70,   62,   80,   72,   81,   76,   77,   74,   74,   78,
       82,   83,   83,   79,   84,   87,   72,   86,   88,   89,
       90,   74,   88,   93,   91,    0,   92,   95,   88,   91,
       80,   97,   86,   94,   96,   74,   74,   98,   82,   83,
       83,   94,   99,   84,   87,  100,   86,   88,   89,   90,
      102,   88,   93,   91,   92,   95,   88,  103,   91,   97,

       86,   94,  104,   96,  106,   98,  105,  107,  121,   94,
       99,  108,  105,  109,  100,  111,  111,  111,    0,  102,
      112,  112,  112,  115,  115,  115,  103,  113,  113,  113,
      123,  104,  124,  106,  105,  125,  107,  121,  113,  108,
      105,  109,  114,  114,  126,  114,  114,  114,  116,  116,
      116,  127,    0,  128,  129,  130,  131,  132,  123,  134,
      124,  133,  133,  134,  125,  135,  136,  113,  135,  137,
      138,  140,  126,  139,  141,  142,    0,  143,  143,  144,
      127,  128,  129,  130,  131,  145,  132,  146,  134,  133,
      133,  147,  134,  148,  135,  136,  135,  149,  137,  138,

      140,  139,  141,  150,  142,  143,  143,  151,  144,  152,
      153,  156,  154,  152,  145,  157,  146,  160,  162,  147,
      163,  148,  154,  165,  166,  149,  167,  168,  170,    0,
      171,  150,  172,  173,  169,  174,  151,  175,  152,  153,
      156,  154,  152,  169,  157,  160,  162,  176,  177,  163,
      154,  165,  179,  166,  180,  167,  168,  170,  171,  181,
      172,  173,  169,  182,  174,  175,  184,  185,  187,  185,
      186,  169,  188,  189,    0,  190,  176,  177,  193,  191,
      179,  192,  180,  191,  194,  195,  195,  195,  181,  196,
      196,  196,  182,  197,  184,  185,  187,  185,  198,  186,

      188,  200,  189,  190,  201,  203,  193,  191,  202,  204,
      192,  191,  194,  205,    0,  206,  207,  208,    0,  209,
      210,  197,  212,  213,    0,  214,  215,  198,  216,  217,
      200,  218,  220,  201,  203,  221,  202,  223,  204,  224,
      225,  226,  205,  206,  207,  228,  208,  209,  229,  210,
      212,  230,  213,  214,  215,  231,  216,  232,  217,  218,
      220,  233,  234,  221,  236,  238,  223,  224,  240,  225,
      226,  242,  243,  228,  244,  245,  229,  246,  247,  230,
      248,    0,  249,  231,  251,  252,  232,  253,  254,  233,
      256,  234,  236,  238,  258,  259,  240,  260,  261,  242,

      243,  262,  264,  244,  245,  265,  246,  247,  267,  248,
      249,  268,  251,  271,  252,  253,  272,  254,  256,  273,
      275,  281,  258,  278,  259,  260,  261,  279,  282,  262,
      283,  264,  284,  285,  265,  286,  287,  267,  288,  289,
      268,  290,  271,  291,  272,  292,    0,  293,  273,  275,
      281,  278,  296,  300,  302,  279,  282,  303,  283,  304,
      305,  284,  285,  286,  287,  306,  307,  288,  289,  290,
      308,  310,  291,  311,  292,  293,  312,  313,  314,  316,
      317,  296,  300,  302,  318,  303,  319,  320,  304,  305,
      321,    0,  322,  324,  306,  307,  325,  327,  308,  310,

      326,  311,  328,  331,  312,  332,  313,  314,  316,  317,
      333,  335,  337,  318,  319,  339,  320,  340,  341,  321,
      322,  342,  324,  344,  345,  325,  327,  349,  326,  351,
      328,  353,  331,  332,  354,  356,  358,  360,  333,  335,
      337,  359,  361,  339,  363,  340,  364,  341,  367,  342,
      368,  374,  344,  345,  373,  349,  375,  351,  376,  353,
      378,  379,  381,  354,  356,  358,  360,  385,  390,  359,
      361,  386,  363,  388,  392,  364,  367,  394,  396,  368,
      374,  395,  373,  397,  375,  398,  376,  401,  403,  378,
      379,  381,  404,  406,  409,  411,  385,  390,  412,  386,

      413,  388,  392,  414,    0,  419,  394,  396,  424,  395,
      426,  397,  428,  398,  432,  401,  434,  403,    0,    0,
      404,  406,  409,  411,    0,    0,    0,  412,    0,  413,
        0,    0,  414,  419,    0,    0,  424,    0,  426,    0,
        0,  428,  432,    0,  434,  451,    0,  451,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,

      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Parser/lparser.l"
#line 2 "Parser/lparser.l"
#include <iostream>
using namespace std;
#include "tok.h" //after compiling bison with -d to understand tokens
#define YY_DECL int yylex()
void yyerror(char *s);
int lineno = 1;
#line 845 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 12 "Parser/lparser.l"


#line 1035 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 450 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 949 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 14 "Parser/lparser.l"
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 15 "Parser/lparser.l"
lineno++;
	YY_BREAK
/* keywords */
case 3:
YY_RULE_SETUP
#line 18 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return DATE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 19 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return INT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 20 "Parser/lparser.l"
{ return ALL; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 21 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return AND; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 22 "Parser/lparser.l"
{ return AMMSC; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 23 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return BOOL; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 24 "Parser/lparser.l"
{ return AMMSC; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 25 "Parser/lparser.l"
{ return AMMSC; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 26 "Parser/lparser.l"
{ return AMMSC; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 27 "Parser/lparser.l"
{ return AMMSC; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 28 "Parser/lparser.l"
{ return ANY; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 29 "Parser/lparser.l"
{ return AS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 30 "Parser/lparser.l"
{ return ASC; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 31 "Parser/lparser.l"
{ return AUTHORIZATION; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 32 "Parser/lparser.l"
{ return BETWEEN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 33 "Parser/lparser.l"
{ return BY; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 34 "Parser/lparser.l"
{ return C; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 35 "Parser/lparser.l"
{ return CACHE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 36 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return CHARACTER; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 37 "Parser/lparser.l"
{ return CHECK; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 38 "Parser/lparser.l"
{ return CLOSE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 39 "Parser/lparser.l"
{ return COMMIT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 40 "Parser/lparser.l"
{ return CONTINUE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 41 "Parser/lparser.l"
{return CREATE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 42 "Parser/lparser.l"
{ return CURRENT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 43 "Parser/lparser.l"
{ return CURSOR; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 44 "Parser/lparser.l"
{ return DATABASE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 45 "Parser/lparser.l"
{ return DECIMAL; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 46 "Parser/lparser.l"
{ return DECLARE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 47 "Parser/lparser.l"
{ return DEFAULT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 48 "Parser/lparser.l"
{ return DELETE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 49 "Parser/lparser.l"
{ return DESC; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 50 "Parser/lparser.l"
{ return DESCRIBE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 51 "Parser/lparser.l"
{ return DISTINCT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 52 "Parser/lparser.l"
{ return DOUBLE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 53 "Parser/lparser.l"
{ return DROP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 54 "Parser/lparser.l"
{ return ESCAPE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 55 "Parser/lparser.l"
{ return EXISTS; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 56 "Parser/lparser.l"
{ return FETCH; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 57 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return FLOAT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 58 "Parser/lparser.l"
{ return FOR; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 59 "Parser/lparser.l"
{ return FOREIGN; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 60 "Parser/lparser.l"
{ return FOUND; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 61 "Parser/lparser.l"
{ return FROM; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 62 "Parser/lparser.l"
{ return GRANT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 63 "Parser/lparser.l"
{ return GROUP; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 64 "Parser/lparser.l"
{ return HAVING; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 65 "Parser/lparser.l"
{ return IN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 66 "Parser/lparser.l"
{ return INDEX; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 67 "Parser/lparser.l"
{ return INDICATOR; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 68 "Parser/lparser.l"
{ return INSERT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 69 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return INTEGER; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 70 "Parser/lparser.l"
{ return INTO; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 71 "Parser/lparser.l"
{ return IS; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 72 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return KEY; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 73 "Parser/lparser.l"
{ return LANGUAGE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 74 "Parser/lparser.l"
{ return LIKE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 75 "Parser/lparser.l"
{ return MODULE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 76 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return NOT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 77 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return NULLX; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 78 "Parser/lparser.l"
{ return NUMERIC; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 79 "Parser/lparser.l"
{ return OFF; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 80 "Parser/lparser.l"
{ return ON; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 81 "Parser/lparser.l"
{ return OPEN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 82 "Parser/lparser.l"
{ return OPTION; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 83 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return OR; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 84 "Parser/lparser.l"
{ return ORDER; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 85 "Parser/lparser.l"
{ return PRECISION; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 86 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return PRIMARY; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 87 "Parser/lparser.l"
{ return PRIVILEGES; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 88 "Parser/lparser.l"
{ return PROCEDURE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 89 "Parser/lparser.l"
{ return PUBLIC; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 90 "Parser/lparser.l"
{ return QUERY; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 91 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return REAL; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 92 "Parser/lparser.l"
{ return REFERENCES; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 93 "Parser/lparser.l"
{ return ROLLBACK; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 94 "Parser/lparser.l"
{ return SCHEMA; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 95 "Parser/lparser.l"
{ return SELECT; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 96 "Parser/lparser.l"
{ return SET; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 97 "Parser/lparser.l"
{ return SHOW; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 98 "Parser/lparser.l"
{ return SMALLINT; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 99 "Parser/lparser.l"
{ return SOME; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 100 "Parser/lparser.l"
{ return SQLCODE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 101 "Parser/lparser.l"
{ return TABLE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 102 "Parser/lparser.l"
{ return TABLES; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 103 "Parser/lparser.l"
{ return TO; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 104 "Parser/lparser.l"
{ return UNION; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 105 "Parser/lparser.l"
{ return UNIQUE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 106 "Parser/lparser.l"
{ return UPDATE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 107 "Parser/lparser.l"
{ return USER; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 108 "Parser/lparser.l"
{ return VALUES; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 109 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return VARCHAR; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 110 "Parser/lparser.l"
{ return VIEW; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 111 "Parser/lparser.l"
{ return WHENEVER; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 112 "Parser/lparser.l"
{ return WHERE; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 113 "Parser/lparser.l"
{ return WITH; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 114 "Parser/lparser.l"
{ return WORK; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 115 "Parser/lparser.l"
{ return DATABASES;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 116 "Parser/lparser.l"
{ return USE;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 117 "Parser/lparser.l"
{ return EXIT;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 120 "Parser/lparser.l"
{ return yytext[0]; }
	YY_BREAK
/* punctuation */
case 104:
#line 125 "Parser/lparser.l"
case 105:
#line 126 "Parser/lparser.l"
case 106:
#line 127 "Parser/lparser.l"
case 107:
#line 128 "Parser/lparser.l"
case 108:
#line 129 "Parser/lparser.l"
case 109:
YY_RULE_SETUP
#line 129 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return COMPARISON; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 132 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return NAME; }
	YY_BREAK
/* numbers */
case 111:
#line 137 "Parser/lparser.l"
case 112:
#line 138 "Parser/lparser.l"
case 113:
YY_RULE_SETUP
#line 138 "Parser/lparser.l"
{ yylval.sval = strdup(yytext);return INTNUM; }
	YY_BREAK
case 114:
#line 141 "Parser/lparser.l"
case 115:
#line 142 "Parser/lparser.l"
case 116:
YY_RULE_SETUP
#line 142 "Parser/lparser.l"
{ return APPROXNUM; }
	YY_BREAK
case 117:
/* rule 117 can match eol */
YY_RULE_SETUP
#line 144 "Parser/lparser.l"
{
			yylval.sval = strdup(yytext);
			return STRING;
	}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 148 "Parser/lparser.l"
;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 149 "Parser/lparser.l"
ECHO;
	YY_BREAK
#line 1694 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 450 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 450 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 449);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 149 "Parser/lparser.l"



void yyerror(char *s)
{
	cout<<"ERROR at "<<lineno<<":"<<s << yytext;
}

